# Generated by Django 4.2.5 on 2025-02-12 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CapturedTraffic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('src_ip', models.GenericIPAddressField()),
                ('dest_ip', models.GenericIPAddressField()),
                ('protocol', models.CharField(max_length=10)),
                ('prediction', models.CharField(max_length=50)),
            ],
        ),
    ]
