# Generated by Django 4.2.5 on 2025-02-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='capturedtraffic',
            name='flow_duration',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='capturedtraffic',
            name='header_length',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='capturedtraffic',
            name='protocol_type',
            field=models.CharField(default='TCP', max_length=50),
        ),
        migrations.AddField(
            model_name='capturedtraffic',
            name='rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='capturedtraffic',
            name='srate',
            field=models.FloatField(default=0.0),
        ),
    ]
