# Generated by Django 4.2.5 on 2025-02-13 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_capturedtraffic_flow_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='capturedtraffic',
            name='drate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='capturedtraffic',
            name='duration',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='capturedtraffic',
            name='protocol_type',
            field=models.IntegerField(default=0),
        ),
    ]
