# Generated by Django 4.2.5 on 2025-02-13 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_capturedtraffic_drate_capturedtraffic_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capturedtraffic',
            name='drate',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='capturedtraffic',
            name='duration',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='capturedtraffic',
            name='flow_duration',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='capturedtraffic',
            name='header_length',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='capturedtraffic',
            name='protocol_type',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='capturedtraffic',
            name='rate',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='capturedtraffic',
            name='srate',
            field=models.FloatField(),
        ),
    ]
