# Generated by Django 4.2.5 on 2025-02-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_capturedtraffic_drate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capturedtraffic',
            name='drate',
            field=models.FloatField(default=0.0),
        ),
    ]
