# Generated by Django 4.2.5 on 2025-02-13 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_capturedtraffic_drate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capturedtraffic',
            name='drate',
        ),
        migrations.RemoveField(
            model_name='capturedtraffic',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='capturedtraffic',
            name='flow_duration',
        ),
        migrations.RemoveField(
            model_name='capturedtraffic',
            name='header_length',
        ),
        migrations.RemoveField(
            model_name='capturedtraffic',
            name='protocol_type',
        ),
        migrations.RemoveField(
            model_name='capturedtraffic',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='capturedtraffic',
            name='srate',
        ),
    ]
